server:
  compression:
    enabled: true
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.1.170:3306/roadtoglory_auth?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: admin
    password: password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

roadtoglory:
  oauth:
    signing-key: secretKey
    security-realm: RoadToGlory Security Realm